### ISSUE TITLE
Update calls to reqwest

### ISSUE THREAD

**Issue by keponk** [aoyagikouhei/twapi-rs#1]
Seems that some calls to `reqwest` have change. 

The version of `reqwest` you have is old and makes a call to an old version of `openssl`, currently there's a good reason to bump it up due to https://github.com/sfackler/rust-openssl/issues/1024

I cloned and tried to build your repo using latest `reqwest` but run into this:
```
   Compiling twapi v0.4.1 (/home/joel/workspace/rustacean/twapi-rs)
error[E0432]: unresolved imports `self::reqwest::header::Headers`, `self::reqwest::header::Authorization`
  --> src/oauth1.rs:15:29
   |
15 | use self::reqwest::header::{Headers, Authorization};
   |                             ^^^^^^^  ^^^^^^^^^^^^^ no `Authorization` in `header`
   |                             |
   |                             no `Headers` in `header`

error[E0432]: unresolved imports `self::reqwest::header::Headers`, `self::reqwest::header::Authorization`, `self::reqwest::header::ContentType`
 --> src/oauth2.rs:5:29
  |
5 | use self::reqwest::header::{Headers, Authorization, ContentType};
  |                             ^^^^^^^  ^^^^^^^^^^^^^  ^^^^^^^^^^^ no `ContentType` in `header`
  |                             |        |
  |                             |        no `Authorization` in `header`
  |                             no `Headers` in `header`

error[E0432]: unresolved imports `self::reqwest::header::Headers`, `self::reqwest::header::Authorization`
  --> src/lib.rs:14:29
   |
14 | use self::reqwest::header::{Headers, Authorization};
   |                             ^^^^^^^  ^^^^^^^^^^^^^ no `Authorization` in `header`
   |                             |
   |                             no `Headers` in `header`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `twapi`.

To learn more, run the command again with --verbose.
```

Looking into it I don't see any reference to `reqwest::header::Headers` or `reqwest::header::Authorization` in their docs. I'm looking into it but I'm quite new to rust.

If you could give me any pointers I could try to help figure it out and provide feedback from any findings. thanks!

**Comment by aoyagikouhei** [comment]
I modified and bumped at 0.4.2. Let's try new version. Thank you for your advice.

**Comment by keponk** [comment]
hi, tried the new version with the main example and now getting following error:

```
cargo run
   Compiling toottr v0.1.0 (/home/joel/workspace/rustacean/toottr)
error[E0308]: mismatched types
  --> src/main.rs:24:9
   |
24 |         twapi::oauth2::get_bearer_token(consumer_key, consumer_secret).unwrap()
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |         |
   |         expected &str, found struct `std::string::String`
   |         help: consider borrowing here: `&twapi::oauth2::get_bearer_token(consumer_key, consumer_secret).unwrap()`
   |
   = note: expected type `&str`
              found type `std::string::String`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `toottr`.

To learn more, run the command again with --verbose.
```

I go ahead and try the suggestion and it compiles. But then it fails, I believe due to unwrap missbehaving:
```
thread 'main' panicked at 'Unable to read file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Any tips? is there something to update in the main example?

**Comment by aoyagikouhei** [comment]
I missed sample in Readme.md.
I changed from
```
let applicaiton_auth = twapi::ApplicationAuth::new(
    twapi::oauth2::get_bearer_token(consumer_key, consumer_secret).unwrap()
);
```
to
```
let applicaiton_auth = twapi::ApplicationAuth::new(
    &twapi::oauth2::get_bearer_token(consumer_key, consumer_secret).unwrap()
);
```

**Comment by keponk** [comment]
Hey sorry maybe I was not clear. You are right to upgrade the example but I had already tried this.
But after doing so I get the error I posted above :
```
thread 'main' panicked at 'Unable to read file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Do you have any ideas what my be causing this? looks like it panic due to some file missing.

**Comment by aoyagikouhei** [comment]
I was successed readme sample.
This sample use only file "test.mp4".
I tried missing file "xxxx.mp4" and got "Err(IO(Os { code: 2, kind: NotFound, message: "No such file or directory" }))".
But this is not runtime error.

Let' try  
`RUST_BACKTRACE=1 cargo run`.
And report full stack trace, main.rs and Cargo.toml.

**Comment by keponk** [comment]
@aoyagikouhei I think I found my error, so this was related to my own code. sorry for the noise.
One more thing, could you post an example of posting one status update? :)

**Comment by keponk** [comment]
I was able to figure it out after more reading on general Rust language. Thanks!
